[package]
name = "voxel"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.17.0", features = ["derive"] }
glam = { version = "0.29.0", features = ["bytemuck"] }
glium = "0.35.0"
num-derive = "0.4.2"
num-traits = "0.2.19"
