[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
ash = "0.38.0"
ash-window = "0.13.0"
gpu-allocator = { version = "0.27.0", default-features = false, features = [
    "vulkan",
] }
log = "0.4.22"
raw-window-handle = "0.6.2"
thiserror = "1.0.63"
